using UnityEngine;

// ï¿½tï¿½ï¿½ï¿½[ï¿½cï¿½ğ§Œä‚·ï¿½ï¿½Xï¿½Nï¿½ï¿½ï¿½vï¿½g
public class Fruit : MonoBehaviour
{
	// ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½oï¿½Ìƒvï¿½ï¿½ï¿½nï¿½u
	public GameObject m_collectedPrefab;

	// ï¿½tï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÉÄï¿½ï¿½ï¿½ï¿½ï¿½ SE
	public AudioClip m_collectedClip;

	// ï¿½ï¿½ï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Æ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ÉŒÄ‚Ñoï¿½ï¿½ï¿½ï¿½ï¿½Öï¿½
	private void OnTriggerEnter2D( Collider2D other )
	{
		// ï¿½ï¿½ï¿½Oï¿½ÉuPlayerï¿½vï¿½ï¿½ï¿½Ü‚Ü‚ï¿½ï¿½Iï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½Æ“ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
		if ( other.name.Contains( "Player" ) )
		{
				// ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ì¬ï¿½ï¿½ï¿½ï¿½
			var collected = Instantiate
			(
				m_collectedPrefab,
				transform.position,
				Quaternion.identity
			);

			// ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ÌƒIï¿½uï¿½Wï¿½Fï¿½Nï¿½gï¿½ï¿½ï¿½ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½^ï¿½[ï¿½Ìï¿½ï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½
			var animator = collected.GetComponent<Animator>();

			// ï¿½ï¿½ï¿½İÄï¿½ï¿½ï¿½ï¿½ÌƒAï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½Ìï¿½ï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½
			var info = animator.GetCurrentAnimatorStateInfo( 0 );

			// ï¿½ï¿½ï¿½İÄï¿½ï¿½ï¿½ï¿½ÌƒAï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ÌÄï¿½ï¿½ï¿½ï¿½Ôiï¿½bï¿½jï¿½ï¿½ï¿½æ“¾ï¿½ï¿½ï¿½ï¿½
			var time = info.length;

			// ï¿½Aï¿½jï¿½ï¿½ï¿½[ï¿½Vï¿½ï¿½ï¿½ï¿½ï¿½ÌÄï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½
			// ï¿½lï¿½ï¿½ï¿½ï¿½ï¿½oï¿½ï¿½ï¿½íœï¿½ï¿½ï¿½ï¿½æ‚¤ï¿½É“oï¿½^ï¿½ï¿½ï¿½ï¿½
			Destroy( collected, time );

			// ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½gï¿½ï¿½ï¿½íœï¿½ï¿½ï¿½ï¿½
			Destroy( gameObject );

			GameManager.instance.PlayerScore();

			// ï¿½tï¿½ï¿½ï¿½[ï¿½cï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ï¿½ SE ï¿½ï¿½ï¿½Äï¿½ï¿½ï¿½ï¿½ï¿½
			var audioSource = FindObjectOfType<AudioSource>();
			audioSource.PlayOneShot( m_collectedClip );
		}
	}
}